### ISSUE TITLE
Without italics

### ISSUE THREAD

**Issue by harg** [pabueco/linear-vscode-theme#1]
Thank you for your great theme !
Is it possible to build a version with all italics disabled?

**Comment by pabueco** [comment]
Thanks, I'm glad you like it.
The new version I just published (0.6) now includes a variant of each theme with italics disabled.
VS Code has some default styles and I cannot disable them in one place, so just let me know if you find any italics that I missed.

**Comment by harg** [comment]
Thank you very much !
