### ISSUE TITLE
Bottom toolbar has low readability in light themes

### ISSUE THREAD

**Issue by shivambl** [pabueco/linear-vscode-theme#2]
The bottom toolbar has very low readability in both light themes. 

Light:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/32495924/154397417-0bc91c58-1cd7-44d0-9ad4-a1db902a20c9.png">

Ash:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/32495924/154397508-a2988256-5f73-4327-8042-82eef695c33f.png">

For reference, this is how it looks like in Dark:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/32495924/154397812-a054d494-bcfe-4a18-b11e-454b7e5f0599.png">

**Comment by pabueco** [comment]
Oh that's not good. Thanks for reporting it!

**Comment by pabueco** [comment]
The new version I just published (0.7) fixes this issue and comes with a few other improvements to the readability and colorization of light themes.
